[project]
name = "ytdlp-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ney461", email = "neymd002@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
ytdlp-api = "ytdlp_api:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
