FONT_FAMILY = "Segoe UI"

FONT_TITLE = (FONT_FAMILY, 16, "bold")
FONT_SUBTITLE = (FONT_FAMILY, 12, "bold")
FONT_LABEL = (FONT_FAMILY, 11, "bold")
FONT_NORMAL = (FONT_FAMILY, 10)
FONT_BUTTON = (FONT_FAMILY, 10, "bold")